### ISSUE TITLE
Heatmap  icon on Desktop APP 0.5.2 (Beta Testing) is too big

### ISSUE THREAD

**Issue by danieltomasz** [pengx17/logseq-plugin-heatmap#103]
Its look like that
<img width="754" alt="image" src="https://user-images.githubusercontent.com/7980381/145256142-aef25258-c8f5-4fb9-9e0f-3f3c55ee9246.png">

**Comment by pengx17** [comment]
fixed in https://github.com/pengx17/logseq-plugin-heatmap/releases/tag/v2.3.0
