### ISSUE TITLE
Only have 3 scales

### ISSUE THREAD

**Issue by usoonees** [pengx17/logseq-plugin-heatmap#236]
https://github.com/pengx17/logseq-plugin-heatmap/blob/4e84699678691fa42cc7eb930b81ce56c78d5541/src/Heatmap.tsx#L113-L120

It should be `min(v, 40)`, `min(v, 30)` would only generate 3 scales.
```javascript
>  Math.ceil(Math.min(25, 30) / 10)
3
>  Math.ceil(Math.min(35, 30) / 10)
3
```
`25` and `35` are same.

**Comment by pengx17** [comment]
Thank you @usoonees for catching this issue! Not sure why I did not find this issue yet ... Do you mind sending a PR to fix it?

**Comment by usoonees** [comment]
> Thank you @usoonees for catching this issue! Not sure why I did not find this issue yet ... Do you mind sending a PR to fix it?

PTAL https://github.com/pengx17/logseq-plugin-heatmap/pull/238
