### ISSUE TITLE
FR: Block counter per range

### ISSUE THREAD

**Issue by wramalho** [pengx17/logseq-plugin-heatmap#45]
Hi,

I have a suggestion: display total blocks in chosen range. I actually manually counted all my blocks because I wanted to know my average number of written blocks :)

**Comment by pengx17** [comment]
This is a good idea! I am also thinking about including more spatial statistics for the blocks, but let's add this first.

**Comment by pengx17** [comment]
Done. 
![image](https://user-images.githubusercontent.com/584378/136880639-ee199eaa-7efb-4f06-9fb3-dd7b69138b99.png)
