### ISSUE TITLE
Next-day day  notes opened with heatmap for next day not saved when Logseq closed before that day

### ISSUE THREAD

**Issue by danieltomasz** [pengx17/logseq-plugin-heatmap#61]
When I used heatmap to create next day  note and closed Logseq before that day started the data was lost 
The note doesn't exist in the git history

**Comment by pengx17** [comment]
@danieltomasz do you have a customized date format for journals?

**Comment by danieltomasz** [comment]
Yes, I use YYYY-MM-DD for Obsidian consistency,
 the Logseq stlil create notes in format YYYY_MM_DD
My settings in edn file
```
 :page-name-order "file"
:journal/file-name-format "yyyy-MM-dd"
 :journal/page-title-format "yyyy-MM-dd"
```
When I tried now create note for next day and close Logseq the note was present there 
(Although heatmap is telling me that theres no block there)

I suspect that in my case Logseq might just overwrite the notes in the graph when changing date (and there were no files on disk)
(to fully reproduce that the midnight and actually changing date would be needed)

**Comment by pengx17** [comment]
@danieltomasz the new version should now adapt the user-defined `:journal/page-title-format`. I think whatever the value of `:journal/file-name-format` should not affect this plugin after all.
